### ISSUE TITLE
Twitter integration

### ISSUE THREAD

**Issue by mcmahonmj** [nmcmahon1215/MackLive#13]
Looking for a way to auto-publish my updates to Twitter. Ideally, I could turn this feature on or off, so not all updates go to Twitter, but there could be a checkbox, or something, where I could send messages to twitter if desired.

**Comment by nmcmahon1215** [comment]
Backend completed. Working on UI

**Comment by mcmahonmj** [comment]
you da man!

**Comment by nmcmahon1215** [comment]
https://github.com/nmcmahon1215/MackLive/releases/tag/Beta-20161008
